secret = "1"
commitment = "0x168758332d5b3e2d13be8048c8011b454590e06c44bce7f702f09103eef5a373"
path = ["2", "0x266d452e34d9880b41e076343099570c3743664aeee94312a026102bdb6e8a0b"]
indices = ["0", "0"]
root = "0x0a38a83896b7a84e5df368f2ee03d0d8e79c5fac9354af59cebb17dc78305ca7"
